# Generated by Django 3.0 on 2021-03-24 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_auto_20210324_2143'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='teachers',
            new_name='teacher',
        ),
    ]
