# Generated by Django 3.0 on 2021-03-30 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_auto_20210324_2152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='teacher',
        ),
    ]
