# Generated by Django 3.0 on 2021-03-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interface', '0005_delete_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('link', models.URLField()),
                ('photo', models.ImageField(upload_to='')),
                ('qr', models.ImageField(upload_to='')),
            ],
        ),
    ]
